server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_quiz
    username: root
    password: root

  #liquibase:
   # change-log: classpath:/liquibase/changelog.xml

  jpa:
    show-sql: true
jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000