server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_quiz
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000